#!/usr/bin/env python3
"""FreeInk icon generator.

Turns Lucide (or any single-color) SVGs into freeink::Icon C structs at one or more
sizes, with the optical center baked in. The renderer draws them orientation-correct,
so the SVGs are NOT pre-rotated here.

Usage:
    gen_icons.py --manifest icons.txt --svgdir <lucide/icons> \
                 --sizes 24,32,40,48 --out generated_icons.h

Manifest: one icon per line, `alias = lucide-name` (or just `name`). The alias is
the identifier used in C; the lucide-name picks the SVG file. Lines starting with #
are comments. Example:
    settings = settings
    recent   = clock
    transfer = arrow-down-up

Requires: rsvg-convert (librsvg) and Pillow.
"""
import argparse
import io
import os
import re
import subprocess
import sys

from PIL import Image

# Luminance below this (composited on white) counts as black/drawn. Lucide strokes
# are dark on transparent; this keeps thin 2px strokes solid at small sizes.
THRESHOLD = 110


def rasterize(svg_path, px):
    png = subprocess.run(
        ["rsvg-convert", "-w", str(px), "-h", str(px), svg_path],
        capture_output=True,
        check=True,
    ).stdout
    img = Image.open(io.BytesIO(png)).convert("RGBA")
    bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    bg.paste(img, mask=img.split()[3])
    return bg.convert("L")


def pack(img, px):
    """Pack to 1-bpp (MSB-first, 1=transparent, 0=black). Returns (bytes, opticalCenterY)."""
    pix = img.load()
    data = []
    sum_y = 0
    count = 0
    for y in range(px):
        for xb in range(0, px, 8):
            byte = 0
            for b in range(8):
                x = xb + b
                white = 1
                if x < px and pix[x, y] < THRESHOLD:
                    white = 0
                    sum_y += y
                    count += 1
                byte |= white << (7 - b)
            data.append(byte)
    center = round(sum_y / count) if count else px // 2
    return data, center


def ident(name):
    return re.sub(r"[^A-Za-z0-9]", "_", name)


def parse_manifest(path):
    entries = []
    for line in open(path):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        if "=" in line:
            alias, lucide = (p.strip() for p in line.split("=", 1))
        else:
            alias = lucide = line.strip()
        entries.append((alias, lucide))
    return entries


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--svgdir", required=True)
    ap.add_argument("--sizes", default="24,32,40,48")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    sizes = [int(s) for s in args.sizes.split(",")]
    entries = parse_manifest(args.manifest)

    out = [
        "#pragma once",
        "",
        '#include "Icon.h"',
        "",
        "// Generated by libs/assets/Icons/tools/gen_icons.py from Lucide SVGs. Do not edit.",
        f"// Sizes: {', '.join(str(s) for s in sizes)}px. Icons: {len(entries)}.",
        "",
    ]
    for alias, lucide in entries:
        svg = os.path.join(args.svgdir, lucide + ".svg")
        if not os.path.exists(svg):
            print(f"ERROR: missing svg for '{alias}': {svg}", file=sys.stderr)
            sys.exit(1)
        out.append(f'// {alias}  (lucide: {lucide})')
        for px in sizes:
            data, center = pack(rasterize(svg, px), px)
            arr = f"icon_{ident(alias)}_{px}_bits"
            body = ", ".join(f"0x{b:02X}" for b in data)
            out.append(f"static const uint8_t {arr}[] = {{{body}}};")
            out.append(
                f"static const freeink::Icon icon_{ident(alias)}_{px} = "
                f"{{{px}, {px}, {center}, {arr}}};"
            )
        out.append("")
    open(args.out, "w").write("\n".join(out))
    print(f"wrote {args.out}: {len(entries)} icons x {len(sizes)} sizes")


if __name__ == "__main__":
    main()
