#!/usr/bin/env python3
"""Rasterize a TrueType/OpenType font into an SDK-embeddable bitmap font header
for FreeInkUI's DisplayTarget (FreeInkUIDisplayTarget.h).

The output is a proportional 1-bit font in the Adafruit-GFX layout: every
glyph's bitmap is packed MSB-first, row-major, and the glyph bitmaps are
concatenated into one blob with a per-glyph metrics table. The DisplayTarget
renders any BitmapFont with this shape, so you can swap the bundled Noto Sans
for your own typeface.

With --alpha the glyphs are instead rasterized anti-aliased and stored as
4-bit coverage (two pixels per byte, high nibble first, 0 = transparent,
15 = full ink; BitmapFont::bpp == 4). DisplayTarget reproduces the edge
coverage on 1-bit panels with its ordered Bayer dither — noticeably smoother
at display sizes (>= ~16px) for ~4x the flash of the 1-bit form.

Usage:
    pip install pillow
    python3 gen_font.py --ttf MyFont.ttf --size 13 --name MyFont \\
        --out ../include/MyFontFont.h

Then in your app:
    #include <MyFontFont.h>
    target.setFont(freeink::ui::kMyFontFont);            // all slots
    target.setFont(theme.tokens.fontTitle, kMyFontFont); // one slot

See docs/freeink-ui.md ("Swapping the font") for the full walk-through.
"""
import argparse
import re
import sys

from PIL import Image, ImageDraw, ImageFont


def c_ident(name: str) -> str:
    ident = re.sub(r"[^0-9A-Za-z]", "", name)
    return ident or "Custom"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ttf", required=True, help="path to the .ttf/.otf to rasterize")
    ap.add_argument("--size", type=int, default=13, help="pixel size (default 13)")
    ap.add_argument("--name", default="Custom", help="symbol name, e.g. NotoSans -> kNotoSansFont")
    ap.add_argument("--first", type=lambda v: int(v, 0), default=0x20)
    ap.add_argument("--last", type=lambda v: int(v, 0), default=0x7E)
    ap.add_argument("--alpha", action="store_true",
                    help="emit anti-aliased 4-bit coverage glyphs instead of a 1-bit mask")
    ap.add_argument("--out", required=True, help="output header path")
    args = ap.parse_args()

    sym = c_ident(args.name)
    font = ImageFont.truetype(args.ttf, args.size)
    ascent, descent = font.getmetrics()
    yadv = ascent + descent

    bitmap = bytearray()
    glyphs = []  # (cp, off, w, h, xadv, xoff, yoff)
    maxw = maxh = 0
    for cp in range(args.first, args.last + 1):
        ch = chr(cp)
        xadv = round(font.getlength(ch))
        bbox = font.getbbox(ch)
        off = len(bitmap)
        if off > 0xFFFF:
            sys.exit(f"error: glyph U+{cp:04X} bitmap offset {off} overflows FontGlyph's uint16 "
                     "bitmapOffset — reduce --size or the --first/--last range")
        if bbox is None or bbox[2] - bbox[0] <= 0 or bbox[3] - bbox[1] <= 0:
            glyphs.append((cp, off, 0, 0, xadv, 0, 0))
            continue
        l, t, r, b = bbox
        if args.alpha:
            # Rasterize anti-aliased and pack 4-bit coverage, two pixels per
            # byte, high nibble first (BitmapFont::bpp == 4).
            img = Image.new("L", (r + 2, b + 2), 0)
            ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=255)
            crop = img.crop((l, t, r, b))
            w, h = crop.size
            px = crop.load()
            acc = nnib = 0
            for y in range(h):
                for x in range(w):
                    acc = (acc << 4) | ((px[x, y] * 15 + 127) // 255)
                    nnib += 1
                    if nnib == 2:
                        bitmap.append(acc)
                        acc = nnib = 0
            if nnib:
                bitmap.append(acc << 4)
        else:
            img = Image.new("1", (r + 2, b + 2), 0)
            ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=1)
            crop = img.crop((l, t, r, b))
            w, h = crop.size
            px = crop.load()
            acc = nbits = 0
            for y in range(h):
                for x in range(w):
                    acc = (acc << 1) | (1 if px[x, y] else 0)
                    nbits += 1
                    if nbits == 8:
                        bitmap.append(acc)
                        acc = nbits = 0
            if nbits:
                bitmap.append(acc << (8 - nbits))
        glyphs.append((cp, off, w, h, xadv, l, t - ascent))
        maxw, maxh = max(maxw, w), max(maxh, h)

    out = []
    P = out.append
    P("#pragma once")
    P("")
    P("// AUTO-GENERATED by tools/gen_font.py — do not edit by hand.")
    P(f"// Source: {args.ttf} at {args.size}px. Covers U+{args.first:04X}..U+{args.last:04X}.")
    if args.alpha:
        P("// Glyph bitmaps are anti-aliased 4-bit coverage (two pixels per byte, high")
        P("// nibble first, 15 = full ink), row-major, concatenated; xOffset/yOffset")
        P("// are the upper-left corner relative to the pen origin on the baseline.")
    else:
        P("// Glyph bitmaps are 1bpp, MSB-first, row-major, concatenated; xOffset/yOffset")
        P("// are the upper-left corner relative to the pen origin on the baseline.")
    P("// Confirm the source font's license permits embedding rasterized bitmaps.")
    P("")
    P("#include <FreeInkUIFont.h>  // struct FontGlyph / BitmapFont")
    P("")
    P("namespace freeink {")
    P("namespace ui {")
    P("")
    P(f"inline constexpr uint8_t k{sym}Bitmap[] = {{")
    for i in range(0, len(bitmap), 16):
        P("    " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 16]) + ",")
    P("};")
    P("")
    P(f"inline constexpr FontGlyph k{sym}Glyphs[] = {{")
    for (cp, off, w, h, xadv, xoff, yoff) in glyphs:
        disp = "space" if cp == 0x20 else (f"0x{cp:02X}" if cp == 0x5C else chr(cp))
        P(f"    {{{off}, {w}, {h}, {xadv}, {xoff}, {yoff}}},  // '{disp}'")
    P("};")
    P("")
    P(f"inline constexpr BitmapFont k{sym}Font = {{")
    P(f"    k{sym}Bitmap, k{sym}Glyphs, 0x{args.first:04X}, 0x{args.last:04X}, "
      f"{yadv}, {ascent}, {maxw}, {maxh}, {4 if args.alpha else 1}}};")
    P("")
    P("}  // namespace ui")
    P("}  // namespace freeink")

    with open(args.out, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {args.out}: k{sym}Font  size={args.size}px bpp={4 if args.alpha else 1} "
          f"yAdvance={yadv} ascent={ascent} "
          f"glyphs={len(glyphs)} bitmap={len(bitmap)}B (~{len(bitmap) + len(glyphs) * 6}B flash)")


if __name__ == "__main__":
    main()
