#!/usr/bin/env python3
"""arabshapec — generates FreeInkBook's Arabic shaping tables from trimmed
UCD extracts (third_party/unicode/, see the README there).

Output: include/text/arab_shaping.h with three tables —
  kArabJoinType   joining type per codepoint for U+0600..077F (U/T/C/D/R/L),
                  applying the ArabicShaping.txt header rule that unlisted
                  Mn/Me/Cf characters are Transparent and all other unlisted
                  characters are non-joining.
  kArabForms      base letter -> presentation-form codepoints (isolated,
                  final, initial, medial; 0 = the form does not exist),
                  derived from the <isolated>/<final>/<initial>/<medial>
                  compatibility decompositions in U+FB50..FEFF. Multi-char
                  decompositions (ligatures) are excluded.
  kLamAlef        the four mandatory lam-alef ligatures: alef variant ->
                  (isolated, final) ligature codepoints U+FEF5..FEFC.

Usage: arabshapec.py <third_party/unicode dir> <out.h>
"""
import sys

JOIN_LO, JOIN_HI = 0x0600, 0x077F
JOIN_CODES = {"U": 0, "T": 1, "C": 2, "D": 3, "R": 4, "L": 5}
FORM_SLOTS = {"<isolated>": 0, "<final>": 1, "<initial>": 2, "<medial>": 3}


def load_join_types(shaping_path, categories_path):
    join = {}
    with open(shaping_path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            fields = [p.strip() for p in line.split(";")]
            cp = int(fields[0], 16)
            if JOIN_LO <= cp <= JOIN_HI:
                join[cp] = fields[2]
    # Header rule: unlisted Mn/Me/Cf are Transparent; all other unlisted are U.
    with open(categories_path, encoding="utf-8") as f:
        for line in f:
            cp_hex, _, cat = line.strip().split(";")
            cp = int(cp_hex, 16)
            if cp not in join and cat in ("Mn", "Me", "Cf"):
                join[cp] = "T"
    return join


def load_forms(pres_path):
    forms = {}     # base cp -> [iso, fin, ini, med]
    lam_alef = {}  # alef variant cp -> [iso, fin]
    with open(pres_path, encoding="utf-8") as f:
        for line in f:
            fields = line.rstrip("\n").split(";")
            cp = int(fields[0], 16)
            decomp = fields[5].split()
            slot = FORM_SLOTS[decomp[0]]
            targets = [int(t, 16) for t in decomp[1:]]
            if len(targets) == 1:
                forms.setdefault(targets[0], [0, 0, 0, 0])[slot] = cp
            elif targets[0] == 0x0644 and len(targets) == 2 and cp >= 0xFEF5:
                lam_alef.setdefault(targets[1], [0, 0])[slot] = cp
    return forms, lam_alef


def main():
    if len(sys.argv) != 3:
        sys.stderr.write(__doc__)
        return 2
    ucd_dir, out_path = sys.argv[1], sys.argv[2]
    join = load_join_types(ucd_dir + "/ArabicShaping.txt",
                           ucd_dir + "/ArabicBlockCategories.txt")
    forms, lam_alef = load_forms(ucd_dir + "/ArabicPresentationForms.txt")

    lines = []
    lines.append("// Generated by tools/arabshapec.py from UCD extracts in")
    lines.append("// third_party/unicode/ — do not edit. Data: Unicode License v3.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("namespace freeink { namespace book {")
    lines.append("")
    lines.append("// Joining types (ArabicShaping.txt field 2).")
    lines.append("enum ArabJoinType : uint8_t {")
    lines.append("  kJoinU = 0,  // non-joining")
    lines.append("  kJoinT = 1,  // transparent (marks — skipped for context)")
    lines.append("  kJoinC = 2,  // join-causing (tatweel)")
    lines.append("  kJoinD = 3,  // dual-joining")
    lines.append("  kJoinR = 4,  // right-joining (joins the preceding letter only)")
    lines.append("  kJoinL = 5,  // left-joining (rare)")
    lines.append("};")
    lines.append("")
    lines.append("inline constexpr uint32_t kArabJoinLo = 0x%04X;" % JOIN_LO)
    lines.append("inline constexpr uint32_t kArabJoinHi = 0x%04X;" % JOIN_HI)
    lines.append("inline const uint8_t kArabJoinType[0x%04X] = {"
                 % (JOIN_HI - JOIN_LO + 1))
    row = []
    for cp in range(JOIN_LO, JOIN_HI + 1):
        row.append("%d" % JOIN_CODES[join.get(cp, "U")])
        if len(row) == 24:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    lines.append("")
    lines.append("// Presentation forms per base letter, sorted by base for binary")
    lines.append("// search. forms[]: isolated, final, initial, medial (0 = absent).")
    lines.append("struct ArabForms {")
    lines.append("  uint16_t base;")
    lines.append("  uint16_t forms[4];")
    lines.append("};")
    lines.append("")
    lines.append("inline const ArabForms kArabForms[] = {")
    for base in sorted(forms):
        f = forms[base]
        lines.append("    {0x%04X, {0x%04X, 0x%04X, 0x%04X, 0x%04X}}," %
                     (base, f[0], f[1], f[2], f[3]))
    lines.append("};")
    lines.append("inline constexpr uint32_t kArabFormsCount = %d;" % len(forms))
    lines.append("")
    lines.append("// Mandatory lam-alef ligatures: lam (U+0644) + alef variant.")
    lines.append("struct ArabLamAlef {")
    lines.append("  uint16_t alef;")
    lines.append("  uint16_t isolated;")
    lines.append("  uint16_t final;")
    lines.append("};")
    lines.append("")
    lines.append("inline const ArabLamAlef kArabLamAlef[] = {")
    for alef in sorted(lam_alef):
        iso, fin = lam_alef[alef]
        lines.append("    {0x%04X, 0x%04X, 0x%04X}," % (alef, iso, fin))
    lines.append("};")
    lines.append("inline constexpr uint32_t kArabLamAlefCount = %d;" % len(lam_alef))
    lines.append("")
    lines.append("}}  // namespace freeink::book")
    lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    sys.stdout.write("arab_shaping: %d join types, %d letters with forms, "
                     "%d lam-alef ligatures\n" % (len(join), len(forms),
                                                  len(lam_alef)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
