#!/usr/bin/env python3
"""hyphc — compiles TeX/hyph-utf8 hyphenation pattern text into FreeInkBook's
FIBH binary format.

Input: one pattern per line (e.g. ".ach4", "ab1o"); '%' starts a comment.
Output layout (little-endian):
  u32 magic 'FIBH' | u16 version=1 | u8 maxPatLen | u8 reserved
  u32 patternCount
  u32 offsets[patternCount]            offsets into the record blob
  records: per pattern — u8 keyLen, key bytes (no digits, lowercase),
           u8 values[keyLen + 1] (Liang inter-character values)
Patterns are sorted bytewise by key so the matcher can binary-search
incrementally per added character.

Usage: hyphc.py <patterns.txt> <out.fibh|out.h>
With a .h extension the same bytes are emitted as a C header (a PROGMEM-able
uint8_t array) so firmware can embed a language without any file on the card.
"""
import os
import re
import struct
import sys


def compile_patterns(lines):
    table = {}
    max_len = 0
    for raw in lines:
        line = raw.split("%", 1)[0].strip()
        if not line:
            continue
        key = []
        values = [0]
        for ch in line:
            if ch.isdigit():
                values[-1] = int(ch)
            else:
                key.append(ch.lower())
                values.append(0)
        key_bytes = "".join(key).encode("utf-8")
        if not key_bytes or len(key_bytes) > 255:
            continue
        # The matcher walks UTF-8 BYTES, so expand the per-character values
        # to byte positions: each character's leading value sits at its first
        # byte, zeros pad continuation bytes. len(values) == len(key_bytes)+1.
        byte_values = []
        for ch, val in zip(key, values[:-1]):
            byte_values.append(val)
            byte_values.extend([0] * (len(ch.encode("utf-8")) - 1))
        byte_values.append(values[-1])
        # Keep the max on duplicate keys.
        old = table.get(key_bytes)
        if old is None:
            table[key_bytes] = byte_values
        else:
            table[key_bytes] = [max(a, b) for a, b in zip(old, byte_values)]
        max_len = max(max_len, len(key_bytes))
    return sorted(table.items()), max_len


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    with open(sys.argv[1], encoding="utf-8") as f:
        patterns, max_len = compile_patterns(f)

    blob = bytearray()
    offsets = []
    for key, values in patterns:
        offsets.append(len(blob))
        blob.append(len(key))
        blob.extend(key)
        blob.extend(values)

    payload = (b"FIBH" + struct.pack("<HBB", 1, max_len, 0)
               + struct.pack("<I", len(patterns))
               + struct.pack(f"<{len(offsets)}I", *offsets) + blob)
    if sys.argv[2].endswith(".h"):
        name = re.sub(r"\W", "_", os.path.basename(sys.argv[2])[:-2])
        lines = ["#pragma once", "",
                 "// Generated by tools/hyphc.py — FIBH hyphenation data. Do not edit.",
                 "#include <stdint.h>", "",
                 "namespace freeink { namespace book {", "",
                 f"inline constexpr uint32_t k_{name}_size = {len(payload)};",
                 f"inline const uint8_t k_{name}[] = {{"]
        for i in range(0, len(payload), 16):
            lines.append("    " + ", ".join(f"0x{b:02X}" for b in payload[i:i+16]) + ",")
        lines += ["};", "", "}}  // namespace freeink::book", ""]
        open(sys.argv[2], "w").write("\n".join(lines))
    else:
        with open(sys.argv[2], "wb") as out:
            out.write(payload)

    size = 12 + 4 * len(offsets) + len(blob)
    print(f"hyphc: {len(patterns)} patterns, max key {max_len}, {size} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
